#config_version=5
# mode2 config file

mode:
    start_events: Right_Inlane_start
    stop_events: Right_Inlane_stop
    priority: 200

# widgets:
    # mode2_start_banner:
      # type: text
      # text: MODE 2 STARTED
      # font_size: 50
      # color: lime
      # y: 80%
      # expire: 1s

# widget_player:
    # mode_mode2_started: mode2_start_banner

variable_player:
    sh_LeftOrbit_flashing_hit:
       score: 10000
    sh_LeftOrbit_lit_hit:
        score: 100
        
# shots:
    # sh_Right_Inlane:
        # switch: s_right_inlane
        # profile: Right_Inlane
        
shot_profiles:
    Right_Inlane:
        states:
          - name: flashing
            show: flash
            speed: 5
          - name: lit
            show: on
        loop: no
        block: yes
        